modLoader = "javafml"
loaderVersion = "[49,)"
issueTrackerURL = "https://github.com/ThexXTURBOXx/ItemTransformHelper/issues"
license = "Unlicense"

[[mods]]
modId = "itemtransformhelper"
version = "${version}"
displayName = "Item Transform Helper"
displayURL = "https://modrinth.com/mod/item-transform-helper"
authors = "TGG, ThexXTURBOXx, Romejanic, lehjr"
description = '''
Interactively change the position, scale, and rotation of an item.
'''
logoFile = "logo.png"
license = "Unlicense"

[[dependencies.itemtransformhelper]]
modId = "forge"
mandatory = true
type = "required"
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemtransformhelper]]
modId = "minecraft"
mandatory = true
type = "required"
versionRange = "[1.20.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemtransformhelper]]
modId = "architectury"
mandatory = true
type = "required"
versionRange = "[11.0.9,)"
ordering = "AFTER"
side = "BOTH"
