modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/ThexXTURBOXx/ItemTransformHelper/issues"
logoFile = "assets/itemtransformhelper/textures/item/item_camera_icon.png"
authors = "TGG, ThexXTURBOXx, Romejanic, lehjr"
license = "Unlicense"

[[mods]]
modId = "itemtransformhelper"
version = "${version}"
displayName = "Item Transform Helper"
displayURL = "https://modrinth.com/mod/item-transform-helper"
description = '''
Interactively change the position, scale, and rotation of an item.
'''

[[dependencies.itemtransformhelper]]
modId = "neoforge"
type = "required"
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemtransformhelper]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemtransformhelper]]
modId = "architectury"
type = "required"
versionRange = "[11.0.9,)"
ordering = "AFTER"
side = "BOTH"
