modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/TheGreyGhost/ItemTransformHelper"
logoFile = "logo.png"
authors = "TGG, ThexXTURBOXx, Romejanic, lehjr"
license = "Unlicense"

[[mods]]
modId = "itemtransformhelper"
version = "${version}"
displayName = "Item Transform Helper"
description = '''
Interactively change the position, scale, and rotation of an item.
'''

[[dependencies.itemtransformhelper]]
modId = "neoforge"
mandatory = true
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemtransformhelper]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemtransformhelper]]
modId = "architectury"
mandatory = true
versionRange = "[10.0.17,)"
ordering = "AFTER"
side = "BOTH"
